### ISSUE TITLE
Basic ember setup

### ISSUE THREAD

**Issue by Tyrdall** [ngenworks/rest_framework_ember#23]
Hej guys,

I'm fully new to ember and drf, so I hope I won't bother. I had some problems getting used to the available adapters, so I was lucky when I found your app. I used your example to integrate it. I got the basic api running, which returns a queryset.

    {
        "meta": {
            "next": null, 
            "next_link": null, 
            "page": 1, 
            "previous": null, 
            "previous_link": null, 
            "count": 1, 
            "total": 1
        }, 
        "recipe": [
            {
                "pk": 1, 
                "name": "Foo", 
                "ingredients": [
                    2, 
                    1
                ], 
                "portions": 1, 
                "date_created": "2014-12-30T20:54:32.523138Z", 
                "date_updated": "2014-12-30T20:54:32.523138Z"
            }
        ]
    }

Now I had to setup ember like that to make use of the api response:

        App = Ember.Application.create();

        App.Router.map(function() {
            this.resource('index', {path: '/'});
        });

        App.IndexRoute = Ember.Route.extend({
            model: function() {
                return $.getJSON('/api/recipes').then(function(data) {
                    return data.recipe;
                });
            }
        });

Now I would like to ask, if there's any way to generate the ember routes dynamically?
Do you know an app example, which includes the ember setup and which helps greenhorns like me to kickstart their ember-drf experience?

Thanks a lot!

**Comment by jerel** [comment]
Generating routes at runtime is an advanced topic; I'd want to be sure that you really want to do that before you head down that path. With that being said this talk from Ember Conf covered that topic a little IIRC.

What I might suggest is to use Ember CLI and generate code with that. It comes with Ember Data and should work right out of the box with this Django adapter. All Ember docs should still apply except instead of using globals like `App.IndexRoute` you'll be using ES6 modules.

`npm install ember-cli`
and then generate some code with:
`ember g model recipe`
`ember g route recipes`
`ember g route recipes/edit`
and then you can run it:
`ember serve`
and open 127.0.0.1:4200 in your browser.

**Comment by Tyrdall** [comment]
Thanks @jerel I'll give it a try!
